services:
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3,sqs,dynamodb,lambda, cloudformation, ssm, logs, iam, apigateway
      - DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
    ports:
      - "4566:4566"
      - "4571:4571"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
